[project]
name = "python-exercises"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.124.0",
    "ipykernel>=7.1.0",
    "openai>=2.9.0",
    "requests>=2.32.5",
]
